spring.application.name=acme-bank-java-mcp
server.port=5024
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=acme-bank-java-mcp
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=sync

spring.ai.mcp.server.resource-change-notification=true
spring.ai.mcp.server.prompt-change-notification=true
spring.ai.mcp.server.tool-change-notification=true

bank.app.url = http://localhost:5025
identity.verification.mcp.url = http://localhost:5023

# to use the store mcp
spring.ai.mcp.client.sse-url=http://localhost:5028
